/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormatsRouteImport } from './routes/formats'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RenameRouteImport } from './routes/rename'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ApiJobsJobIdRouteImport } from './routes/api/jobs.$jobId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatsRoute = FormatsRouteImport.update({
  id: '/formats',
  path: '/formats',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RenameRoute = RenameRouteImport.update({
  id: '/rename',
  path: '/rename',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdRoute = ApiJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiJobsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formats': typeof FormatsRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/rename': typeof RenameRoute
  '/settings': typeof SettingsRoute
  '/watch': typeof WatchRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formats': typeof FormatsRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/rename': typeof RenameRoute
  '/settings': typeof SettingsRoute
  '/watch': typeof WatchRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formats': typeof FormatsRoute
  '/history': typeof HistoryRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/rename': typeof RenameRoute
  '/settings': typeof SettingsRoute
  '/watch': typeof WatchRoute
  '/api/events': typeof ApiEventsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/formats'
    | '/history'
    | '/inbox'
    | '/login'
    | '/rename'
    | '/settings'
    | '/watch'
    | '/api/events'
    | '/api/health'
    | '/api/jobs'
    | '/jobs/$jobId'
    | '/api/jobs/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/formats'
    | '/history'
    | '/inbox'
    | '/login'
    | '/rename'
    | '/settings'
    | '/watch'
    | '/api/events'
    | '/api/health'
    | '/api/jobs'
    | '/jobs/$jobId'
    | '/api/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/formats'
    | '/history'
    | '/inbox'
    | '/login'
    | '/rename'
    | '/settings'
    | '/watch'
    | '/api/events'
    | '/api/health'
    | '/api/jobs'
    | '/jobs/$jobId'
    | '/api/jobs/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormatsRoute: typeof FormatsRoute
  HistoryRoute: typeof HistoryRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  RenameRoute: typeof RenameRoute
  SettingsRoute: typeof SettingsRoute
  WatchRoute: typeof WatchRoute
  ApiEventsRoute: typeof ApiEventsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiJobsRoute: typeof ApiJobsRouteWithChildren
  JobsJobIdRoute: typeof JobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formats': {
      id: '/formats'
      path: '/formats'
      fullPath: '/formats'
      preLoaderRoute: typeof FormatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rename': {
      id: '/rename'
      path: '/rename'
      fullPath: '/rename'
      preLoaderRoute: typeof RenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId': {
      id: '/api/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/jobs/$jobId'
      preLoaderRoute: typeof ApiJobsJobIdRouteImport
      parentRoute: typeof ApiJobsRoute
    }
  }
}

interface ApiJobsRouteChildren {
  ApiJobsJobIdRoute: typeof ApiJobsJobIdRoute
}

const ApiJobsRouteChildren: ApiJobsRouteChildren = {
  ApiJobsJobIdRoute: ApiJobsJobIdRoute,
}

const ApiJobsRouteWithChildren =
  ApiJobsRoute._addFileChildren(ApiJobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormatsRoute: FormatsRoute,
  HistoryRoute: HistoryRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  RenameRoute: RenameRoute,
  SettingsRoute: SettingsRoute,
  WatchRoute: WatchRoute,
  ApiEventsRoute: ApiEventsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiJobsRoute: ApiJobsRouteWithChildren,
  JobsJobIdRoute: JobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
