/**
 * Messages picked by a runtime key (provider, action, job status …), for pickMsg() and option lists.
 */
import * as m from "~/paraglide/messages";

export const msgGroup = {
  actions: {
    test: m.actions_test,
    move: m.actions_move,
    copy: m.actions_copy,
    rename: m.actions_rename,
  },
  /** Actions of earlier versions, still in the history. */
  pastActions: {
    hardlink: m.actions_hardlink,
    symlink: m.actions_symlink,
  },
  conflictPolicies: {
    skip: m.conflictPolicies_skip,
    overwrite: m.conflictPolicies_overwrite,
    suffix: m.conflictPolicies_suffix,
    "keep-better": m.conflictPolicies_keep_better,
  },
  jobStatus: {
    pending: m.jobStatus_pending,
    scanning: m.jobStatus_scanning,
    matching: m.jobStatus_matching,
    ready: m.jobStatus_ready,
    executing: m.jobStatus_executing,
    done: m.jobStatus_done,
    failed: m.jobStatus_failed,
    cancelled: m.jobStatus_cancelled,
    undone: m.jobStatus_undone,
  },
  modes: {
    media: m.modes_media,
    rules: m.modes_rules,
    both: m.modes_both,
  },
  nav: {
    main: m.nav_main,
    dashboard: m.nav_dashboard,
    workbench: m.nav_workbench,
    inbox: m.nav_inbox,
    history: m.nav_history,
    formats: m.nav_formats,
    watch: m.nav_watch,
    settings: m.nav_settings,
    connected: m.nav_connected,
    disconnected: m.nav_disconnected,
    demo: m.nav_demo,
    language: m.nav_language,
    logout: m.nav_logout,
  },
  providers: {
    tmdb: m.providers_tmdb,
    tvdb: m.providers_tvdb,
    tvmaze: m.providers_tvmaze,
    anidb: m.providers_anidb,
  },
  releaseLanguages: {
    de: m.releaseLanguages_de,
    en: m.releaseLanguages_en,
    fr: m.releaseLanguages_fr,
    es: m.releaseLanguages_es,
    it: m.releaseLanguages_it,
    ja: m.releaseLanguages_ja,
  },
  rules_types: {
    replace: m.rules_types_replace,
    insert: m.rules_types_insert,
    remove: m.rules_types_remove,
    case: m.rules_types_case,
    separators: m.rules_types_separators,
    numbering: m.rules_types_numbering,
    date: m.rules_types_date,
    extension: m.rules_types_extension,
    transliterate: m.rules_types_transliterate,
    cutAfter: m.rules_types_cutAfter,
    pad: m.rules_types_pad,
    cleanup: m.rules_types_cleanup,
    strip: m.rules_types_strip,
    rearrange: m.rules_types_rearrange,
    list: m.rules_types_list,
    metadata: m.rules_types_metadata,
  },
  settings_providerHint: {
    tmdb: m.settings_providerHint_tmdb,
    tvdb: m.settings_providerHint_tvdb,
    tvmaze: m.settings_providerHint_tvmaze,
    anidb: m.settings_providerHint_anidb,
  },
  states: {
    parsed: m.states_parsed,
    matched: m.states_matched,
    needs_review: m.states_needs_review,
    ready: m.states_ready,
    done: m.states_done,
    skipped: m.states_skipped,
    failed: m.states_failed,
    undone: m.states_undone,
  },
  template_tokens: {
    n: m.template_tokens_n,
    imdb: m.template_tokens_imdb,
    tmdb: m.template_tokens_tmdb,
    tvdb: m.template_tokens_tvdb,
    rating: m.template_tokens_rating,
    y: m.template_tokens_y,
    t: m.template_tokens_t,
    s00e00: m.template_tokens_s00e00,
    s00: m.template_tokens_s00,
    e00: m.template_tokens_e00,
    sxe: m.template_tokens_sxe,
    vf: m.template_tokens_vf,
    vc: m.template_tokens_vc,
    ac: m.template_tokens_ac,
    lang: m.template_tokens_lang,
    edition: m.template_tokens_edition,
    group: m.template_tokens_group,
    part: m.template_tokens_part,
    absolute: m.template_tokens_absolute,
    d: m.template_tokens_d,
    source: m.template_tokens_source,
    orig: m.template_tokens_orig,
  },
  titleLanguages: {
    "de-DE": m.titleLanguages_de_DE,
    "en-US": m.titleLanguages_en_US,
    "fr-FR": m.titleLanguages_fr_FR,
    "es-ES": m.titleLanguages_es_ES,
    "ja-JP": m.titleLanguages_ja_JP,
  },
} as const;
